version: "3"

services:
  telemetry-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
      - /app/tmp:uid=101,gid=101
    environment:
      SUBSTRATE_TELEMETRY_URL: wss://telemetry-stage.web3tech.space/feed
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf

  telemetry-backend-shard:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    read_only: true
    command: [
      'telemetry_shard',
      '--listen', '0.0.0.0:8001',
      '--core', 'http://telemetry-backend-core:8000/shard_submit'
      ]
#    ports:
#      - 8001:8001
    expose:
      - 8001
    restart: unless-stopped

  telemetry-backend-core:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    read_only: true
    command: [
      'telemetry_core',
      '--listen', '0.0.0.0:8000'
      ]
#    ports:
#      - 8000:8000
    expose:
      - 8000
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email admin@web3tech.space -d telemetry-stage.web3tech.space --agree-tos
    depends_on:
      - telemetry-frontend
